### ISSUE TITLE
Users have to re-enter Login-Data for Roundcube after OC Upgrade and/or password change in OC

### ISSUE THREAD

**Issue by eomot** [hypery2k/owncloud#314]
Hi!

This is more a feature request than an issue, I guess.

After Upgrading Owncloud 7 to 8 and using a newer version of your fine oc roundcube app, the oc roundcube app does work.
However, all users have to re-enter their roundcube login information again.
Of course this is an installation WITHOUT Auto-login, since the login information is quite different (roundcube != owncloud login).
On my installation this is a serious hinderance in upgrading Owncloud to 8 at all (I only did it with a backup copy, not the real production system). I noticed that OC 8 migrated something with the private keys during upgrade.

Could you implement something, that the stored usernames and passwords in oc_roundcube table can still be used after upgrade ?

It's basically the same as when changing your owncloud password. Then (I'm guessing because of changed private key?) roundcube login information has also to be entered once again. I can absolutely live with that, but the first problem (after an upgrade) is a Problem for some inexperienced users who then require help.

I hope I was more clear than in my email from before.

Thanx!

**Comment by rotdrop** [comment]
Didn't look at RC-App for quite a while now. I fear this private/public key stuff originally was initiated by me (instead of storing more-or less clear-text passwords in the DB).

Actually, I am a little bit surprised. As far as I know it is handled like this in RC-App:
- we store the private key, protected by the login-password as passphrase, in the ordinary user-prefs table, as well as the public key (of course)
- during login, the private key is fetched from the user prefs table and decrypted by the login-password (which is available just at that time)
- the stored email credentials are then decrypted by the private key, the app logs into RouncCube and refreshes the RoundCube session periodically, using a JavaScript timer

So -- at least intentionally -- the private keys should be kept across OC updates, as long as the user preferences survive the OC update, and the login-password of the users is not changed outside the control of OC (e.g. by directly editing the data-base entries)

Having said all this: it is simply that I am surprised, of course, I believe that you had your problems after the update. It's just that the "something that makes that email credentials can be used after update" should already be there (quasi automatically).  The question is then: what went wrong?

Also, I have upgraded my test-system to OC-8 without problems. However: this is rather hackish and git-based. However, I did not run the "regular" update procedure (copied the working copy, switched to the stable-8 branch with git, crossed thumbs that the automatic data-base update would do the right thing). Read: doesn't mean a thing that it worked for me in this case. But at least there is _some_ potential that under _certain_ circumstances the email credentials are preserved across OC upgrade.

But maybe Martin has some further deas about this.

I know that this message does not provide a solution. However, prior to writing this I took some 15 minutes to review the current RC-App codebase. At least there does not seem to be an obvious reason for your problem. Again, this doesn't mean a thing. 15 minutes is just nothing w.r.t. software development.

Best,

Claus

**Comment by hypery2k** [comment]
there seems to be some issues with owncloud upgrade and the private key, see https://github.com/owncloud/core/issues/13450

I have to prepare a setup for verifying that

**Comment by rotdrop** [comment]
Are you sure that this is related? In RC-App we just store the plain (BASE64) openssl  key in the user prefs space (this is table oc_preferences). E.g., in my test setup I have

    -----BEGIN ENCRYPTED PRIVATE KEY-----
    [SNIP]
    IICxjBABgkqhkiG9w0BBQ0wMzAbBgkqhkiG9w0BBQwwDgQIviQO969m0BgCAggAMB
    ----END ENCRYPTED PRIVATE KEY-----

just tagged with my username `claus` and the app-id `roundcube`.  I mean, we are not talking here about some fancy internal private key format invented by the OC officials, but about plain PHP openssl keys.

The problem-report your are referencing here is talking about the file-system encryption. Not the thing we are doing in the RC-App. I dare say that this is totally unrelated (but as usual: I may very well be on the wrong trace).

Cheers,

Claus

**Comment by eomot** [comment]
I'm afraid that "occ encryption:migrate-keys" did not help. It completes just fine.
I had migration problems, which I already solved for the files app.
Just to make sure, I tried different users. None of them get logged in to roundcube. Only after manualle re-entering roundcube login on "personal" page in OC does it work again.
I'll try to do the whole upgrade process from scratch again, and let you know. Maybe something got borked during upgrade ...

**Comment by rotdrop** [comment]
Well, that was to be expected ... sorry. In principle, as long as the oc_preferences table is not garbled during update stuff should work as before. BTW:  do you have access to the underlying SQL data-base? If so, if you search this table for
userid LIKE johndoe (i.e. one of your users)
appid LIKE roundcube
you will get two entries:
privateSSLKey
publicSSLKey
The privateSSLKey is just the exported, passphrase protected key and should in principle survive the upgrade progress. Now, first: the key should start with something like this:
    -----BEGIN ENCRYPTED PRIVATE KEY-----
And it particular: the key should still be there after the upgrade. In order to verify -- as a first step -- that the key in principle is still functional, you could save it to a file `enckey.pem` and try to decrypt it on the command line using the `openssl` command

    openssl rsa -in enckey.pem -out key.pem

It will ask you for the pass-phrase, which is identical to the login-passwort of the user the key belongs to (obviously, you have then to know the login password of that user)

#### slightlyOfftopic ####
Other question: In your first posting you stated something like this
> It's basically the same as when changing your owncloud password.

Reading this and having a look at the "changePasswordListener()" of the RC-App I just realize that the changePasswordListener() cannot work, as it tries to fetch the old private key with the new password, which obviously just cannot work. It shows that prior to commit
    35ac271a47c9cecad3375da57aa9d5ae7d1d251f
the decrypted key was stored in the session data, and then could be used in the changePasswordListener() in order to recrypt the email credentials.
#### /slightlyOfftopic ####

Still this does not explain the upgrade problems. If you do not change the password, then the ssl private/public key-pair should still be usable (unless you damage the oc_preferences table during upgrade, or assign different user ids after the upgrade)

**Comment by enoch85** [comment]
I have a similar issue.

```
Error	roundcube	Got the following error code: 10	2015-03-08T19:03:01+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-03-08T19:03:01+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2015-03-08T19:03:01+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2015-03-08T19:03:01+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-03-08T19:03:01+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-03-08T19:02:41+00:00
Error	PHP	openssl_private_decrypt(): key parameter is not a valid private key at /var/www/owncloud/apps/roundcube/lib/RoundCubeApp.class.php#158	2015-03-08T19:02:40+00:00
Error	PHP	openssl_private_decrypt(): key parameter is not a valid private key at /var/www/owncloud/apps/roundcube/lib/RoundCubeApp.class.php#158	2015-03-08T19:02:40+00:00
Error	PHP	Undefined index: password at /var/www/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php#45	2015-03-08T19:02:40+00:00
```

Having owncloud installation at https://example1.se and roundcube installation at https://roundcube.example1.se with a valid SSL cert.

The main installation at https://roundcube.example1.se is working and I can see my emails, but the ownCloud app dosen't store the password of my email in DB. It only stores my regular owncloud login.

![image](https://cloud.githubusercontent.com/assets/4511254/6547142/aae50daa-c5cf-11e4-82f5-444e698a7547.png)

I have configured OC_Roundcube to https://roundcube.example1.se, so the adress is correct. 

Is this a bug, or have I done something wrong?

**Setup**
Owncloud 8.0.1
Roundcube 1.1.0
OC Roundcube v2.5.4.268 (latest from today anyway)

**Comment by enoch85** [comment]
Ok, so I re-installed the app and now the app appears and it says that I'm logged in as daniel@example1.se, but...

```
Error	PHP	Undefined index: password at /var/www/owncloud/apps/roundcube/lib/RoundCubeAuthHelper.class.php#45	2015-03-08T19:36:50+00:00
```

Still same error in DB. Why isn't the password stored?

**Comment by enoch85** [comment]
Now I tried to create a new user that was exactly the same as the roundcube user, and now it got stored correctly in DB. (Should be stored even if I'm logged in as different user, you have to fix that.)

But now I got theese errors insetad:

```
Error	roundcube	Got the following error code: 10	2015-03-08T20:02:45+00:00
Error	roundcube	Not rendering roundcube iframe view due to errors	2015-03-08T20:02:45+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): RoundCube can not login to roundcube due to a login exception to roundcube	2015-03-08T20:02:45+00:00
Error	roundcube	OC_RoundCube_App.class.php->showMailFrame(): There were login errors	2015-03-08T20:02:45+00:00
Error	roundcube	OC_RoundCube_App.class.php->refresh(): Failed to refresh the RC session.	2015-03-08T20:02:45+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-03-08T20:02:38+00:00
Error	roundcube	OC_RoundCube_App.class.php->login(): : RoundCube can't login to roundcube due to a login error to roundcube	2015-03-08T19:55:10+00:00
```

**Comment by enoch85** [comment]
Some debug output:

```
Info	roundcube	Rendering roundcube iframe view	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_App.class.php->showMailFrame(): Preparing iFrame for roundcube.	2015-03-08T20:14:59+00:00
Info	roundcube	OC_RoundCube_App.class.php->refresh(): Successfully refreshed the RC session.	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_App.class.php->refresh(): Trying to refresh RoundCube session under /	2015-03-08T20:14:59+00:00
Debug	roundcube	tpl.mail.php: Found valid user login data.	2015-03-08T20:14:59+00:00
Info	roundcube	tpl.mail.php: Preparing pre-check before rendering mail view	2015-03-08T20:14:59+00:00
Debug	roundcube	tpl.mail.php: Opening iframe for RC-host roundcube.example1.se with port 443	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_App.class.php->checkLoginData(): Found login data for user	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_App.class.php->checkLoginData(): Checking login data for user	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_DB_Util.class.php: Table roundcube exists.	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_DB_Util.class.php: Used SQL: SELECT * FROM `*PREFIX*roundcube` LIMIT 1	2015-03-08T20:14:59+00:00
Debug	roundcube	OC_RoundCube_DB_Util.class.php: Checking if roundcube table exists.	2015-03-08T20:14:59+00:00
Debug	roundcube	Running on OwnCloud 8	2015-03-08T20:14:59+00:00
```

**Comment by mckaygerhard** [comment]
oc 8 support for this app are still in progress, some reports said works and there's some issues still unresolved..

please take in consideration that u'r setup its not common, so u must read the extra procedure in the wiki instalation page ..

in future main developer and author will sustituye the fopèn procedure to a cURL to avoid some problems similar

**Comment by luisza** [comment]
Hi, I am using owncloud 8.0.2.0 and Roundcube 1.1.1.  I get the openssl_private_decrypt(): key parameter is not a valid private key at issue, so I look up for the problem cause.

I saw that you use user password as passphrase when create a key pair, and when you decrypt again use user password as a passphrase, but what was my problem?

I don't know why when generateKeyPair is called the passphrase is empty but when getPrivateKey is called the user password is set as passphrase.

I think what happen if the user change the password, lost the passphrase ?
Why you don't use a system passwordsalt that in theory is safe and don't change.

I know this is not a best patch, but I do this and work.

in RoundCubeApp.class.php

	public static function generateKeyPair($user, $passphrase)
	{
		$passphrase = OCP\Config::getSystemValue('passwordsalt', '');
        ...
    }

	public static function getPrivateKey($user, $passphrase)
	{
        $passphrase = OCP\Config::getSystemValue('passwordsalt', '');
        ...
    }

**Comment by hypery2k** [comment]
can you please retest with this version?

https://martinreinhardt-online.de/jenkins/view/BMP_OwnCloud/job/OwnCloud_test/1265/artifact/roundcube/target/
