### ISSUE TITLE
Saving... RoundCube Mailaccount

### ISSUE THREAD

**Issue by cheesewizz** [hypery2k/owncloud#354]
Hi,

my problem is when i update email identity and click save taking long time nothing happened.

thanks
![savinggg](https://cloud.githubusercontent.com/assets/14123082/10408338/59a683c6-6f2d-11e5-8147-64660655ebf2.png)

**Comment by mckaygerhard** [comment]
please that info are too little, enable debug console (hit F12 on chomium) and see he errors, post feedback including setup environment and procedure

take in consideration tat developement of this app have been stoped and if u are interes made a pul request with cod solution

**Comment by IzzySoft** [comment]
I see the same issue here, but cannot hit anything in chomium ("chomium not found" ;) – using Firefox 41 here. Database is updated, just that string doesn't go away, so it *looks like* nothing happens.

And did I understand correctly: OC_Roundcube is no longer supported/maintained? Because in that case I can use my time for other things than trying to figure out why I cannot get it working (Displays `You don't have any email account configured correctly yet. Please check you username and password.` – but the logs say different funny stuff; speaking of which, they ***contain the password in plain text***, which I consider a security risk – but from that I know updating that info worked).

**Comment by mckaygerhard** [comment]
only webkit based browser that the time browser capabilities to track console errores, install chromium (apt-get install chromium-browser)

apport! do u have the solution? the oc-apps are not mantained any more, so **until oc 7.X works, oc 8.X does not supported officially too many changes in oc api to track to a simple man...**

if u have dissagree with this, reclaim to oc entrerprices that changes everyting in each version or better collaborate with working code solution to the problems

**Comment by mckaygerhard** [comment]
closing due duplicate of #333

**Comment by IzzySoft** [comment]
I know you've meant Chromium, but I don't like it. Firefox also tracks console errors (press <kbd>Ctrl</kbd>-<kbd>K</kbd> to open console). But as you just confirmed this app isn't maintained anymore, I uninstalled it and solved the issue using the ExternalSites app shipping with OC. Not as elegant (auto-login, hide bars etc. are missing that way), but worked promptly.

Btw: I understand your reasons for stopping maintenance – I often think about doing the same for my projects for the very same reasons.

**Comment by mckaygerhard** [comment]
i research at firefox and can do the same but installing the developer tools app and here there a history line part when u can view the headers and response.. this i post as feedback
